### ISSUE TITLE
Can't see settings to use the mod

### ISSUE THREAD

**Issue by MokahTGS** [ArmyOfOptimists/NoDurabilityPlus#1]
Opening up the mod settings panel I can't expand the mods section to make any changes to durability.  I have two other mods that use the settings API and I can make changes to them.

How do I use this mod without the API settings??

**Comment by ArmyOfOptimists** [comment]
Thanks for bringing this to my attention.

In v1.0, you should be able to change the settings from the main menu and have it work.  I'm working on an update that will open this up so you can change settings in-game as well.

**Comment by ArmyOfOptimists** [comment]
Addressed in v1.1.1.  Settings are now changeable in-game.
